### ISSUE TITLE
Option: Same background color as line highlight

### ISSUE THREAD

**Issue by ShalokShalom** [byi8220/indented-block-highlighting#3]
I suggest to create an additional settings mode, which provides the solution to the following question:

> What if I prefer to highlight all, indentation and line, in the same color and brightness?

Thanks a lot

**Comment by byi8220** [comment]
Implemented a accentCurrentLine option. It's on by default but can be disabled in the settings.

**Comment by ShalokShalom** [comment]
^-^

**Comment by ShalokShalom** [comment]
This looks the same to me: 

![screenshot_20180415_184243](https://user-images.githubusercontent.com/6344099/38780834-e6df6388-40dc-11e8-8270-f5eba227ff59.png)

**Comment by byi8220** [comment]
I cannot reproduce this using the settings shown in your screenshot. It seems to be working fine for me.

![currentline](https://user-images.githubusercontent.com/24833703/38781027-46d48ee2-40ad-11e8-8ec4-6ea2492210bf.png)

**Comment by ShalokShalom** [comment]
Do you use the current VSCode?

**Comment by ShalokShalom** [comment]
Ah, you probably set "editor.renderLineHighlight": "none"?

**Comment by byi8220** [comment]
VSC is up to date and I've messed with the editor.renderLineHighlight setting, but everything still appears to be working as intended for me.

For me it updates and stops accenting the current line the moment I save settings and change lines.

**Comment by ShalokShalom** [comment]
Linux?
